# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Project.destroy_all 

Project.create({title: "PlayTime", teaser: "Social Media Site", description: "Social media isn't as personal or fun as it used to be, so I built this social media game that pushes for more user to user engagement. Players gains exp for posting to friends' walls and level up to increase energy limits. Having to wait for energy to replenish also encourage players to take a break from their devices once in a while 👍", year: 2019, tech_stack: "React, Javascript, Ruby on Rails, PostgreSQL, CSS with Flexbox, Heroku, and Netlify", demo_url: "https://playtime-beta.netlify.com", git_url: "https://github.com/robertchen234/playtime-frontend", video_url: nil, image_url: "playtime.png", claps: 0})
Project.create({title: "Welcome Board", teaser: "Advice Forum", description: "Every 3 weeks at bootcamp, we learn a totally different framework or language which comes with its unique struggles. I built this board for students to leave insight about each module for more junior students.", year: 2019, tech_stack: "React, Javascript, Ruby on Rails, PostgreSQL, CSS, Heroku, and Netlify", demo_url: "https://welcome-board.netlify.com", git_url: "https://github.com/robertchen234/welcome-board-frontend", video_url: nil, image_url: "welcomeboard.png", claps: 0})
Project.create({title: "Code Code Revolution", teaser: "Typing Game", description: "This game tests how fast a player can type code and compete on the leaderboard. I had the joy of doing a live demo and someone brought over their own custom keyboard, it got intense!", year: 2018, tech_stack: "vanillaJS, Ruby on Rails, SQLite3, CSS", demo_url: nil, git_url: "https://github.com/robertchen234/code-code-revolution-frontend", video_url: "https://www.youtube.com/embed/tgPy_OV-nLM", image_url: "codecoderevolution.png", claps: 0})
Project.create({title: "HyperFundIt", teaser: "Co-Founded, Fundraising & Marketing", description: "Crowdfunding SaaS startup to provide marketing and financial resources for entrepreneurs in blockchain tech. Using WooCommerce and BuddyPress from WordPress plugins while integrating the Steem cryptocurrency wallet, I created a user friendly fundraising platform that hosted campaigns for clients from Nigeria, Ghana, the Philippines, and back home to the USA.", year: 2018, tech_stack: "WordPress", demo_url: "https://hyperfundit.com", git_url: nil, video_url: nil, image_url: "hyperfundit.png", claps: 0})